### ISSUE TITLE
Enable public CORS to let others really use the API

### ISSUE THREAD

**Issue by louy2** [jeffh/YACS#80]
Basicly that "others" is me... I am trying to access the API directly from my website with javascript, which requires CORS setting at the API side.

More information: http://enable-cors.org/index.html
How-to: http://enable-cors.org/server.html

**Comment by louy2** [comment]
Django App: https://github.com/ottoyiu/django-cors-headers

**Comment by jeffh** [comment]
Hey @louy2, I'm currently overloaded with work and currently can't address this. Could you send a pull request with the changes?

Thanks,
Jeff
