### ISSUE TITLE
yacs.me subdomain

### ISSUE THREAD

**Issue by louy2** [jeffh/YACS#83]
@jeffh
You probably know that this semester RCOS has launched YACS++ building around YACS. My project [CourseMap](/louy2/coursemap) is part of it. Could we use `yacs.me` domain to host these projects? e.g. `coursemap.yacs.me`?

**Comment by jeffh** [comment]
@louy2, count me as uninformed :frowning:, but sounds pretty exciting.

Is there some backend component to this? What's the hosting / deployment strategy to CourseMap? I can definitely make a subdomain that points to an A record if you have one.

**Comment by louy2** [comment]
CourseMap currently is front-end only, everything in Javascript, and hosted on Github Pages. Others use Django as well, and as far as I can tell are in quite early stage of development and have not decided on how to deploy.

You can point the subdomain to <https://louy2.github.io/CourseMap>.

**Comment by jeffh** [comment]
I can only do a URL redirect if it's only available via DNS record (aka - no CNAME / A record). A URL isn't a valid DNS record.

**Comment by louy2** [comment]
Oh right. This time I've got the CNAME set up. I just picked `coursemap.yacs.me`.

**Comment by jeffh** [comment]
Ok, I've set it up. I'd recommend adding a feedback link because I just prefer to not answer any support about that subdomain :stuck_out_tongue:

**Comment by louy2** [comment]
Will add feedback link soon. Btw, I have just received a support email saying:

>The page build completed successfully, but returned the following warning:

>Your site's DNS settings are using a custom subdomain, coursemap.yacs.me, that's not set up with an correct CNAME record. We recommend you set this CNAME record to point at louy2.github.io. Instructions on configuring a subdomain for use with GitHub Pages can be found at: https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/

**Comment by jeffh** [comment]
It seems fine on my side, I'd say wait a bit longer to see if github refreshes.

![screen shot 2015-04-07 at 6 49 14 pm](https://cloud.githubusercontent.com/assets/68616/7037381/d24ed328-dd56-11e4-82cd-16ff21a1ac92.png)

**Comment by louy2** [comment]
Just tried <http://coursemap.yacs.me> and it's working. Thanks!
